require 'securerandom'
require 'openra/constants'
require 'openra/replays'
require 'openra/commands/utils'
require 'openra/commands/replays/extract_metadata'
require 'openra/commands/replays/extract_data'
