name: ci

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - lib/**
      - spec/**
      - Rakefile
      - Gemfile
      - "*.gemspec"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.2'
        - '3.1'
        - '3.0'
        - '2.7'
        - jruby
        include:
          - ruby: "3.0"
            coverage: "true"
    env:
      COVERAGE: ${{matrix.coverage}}
    steps:
      - uses: actions/checkout@v1
      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
      - name: Install latest bundler
        run: |
          gem install bundler --no-document
          bundle config set without 'tools benchmarks docs'
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run all tests
        run: bundle exec rake
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: env.COVERAGE
        with:
          name: coverage-report
          path: coverage
